// Code generated by generate_image_loader.go; DO NOT EDIT.
package yourpkg

import (
	"fmt"
	"image"
	"os"
	"path/filepath"

	"github.com/hajimehoshi/ebiten/v2"
)

type ImageMap struct {
	Background *ebiten.Image
	Player     *ebiten.Image
	Enemy      *ebiten.Image
}

func LoadImage(path string) (*ebiten.Image, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		return nil, err
	}
	return ebiten.NewImageFromImage(img), nil
}

func LoadAllImages(basePath string) (*ImageMap, error) {
	var m ImageMap
	var err error

	m.Background, err = LoadImage(filepath.Join(basePath, "background.png"))
	if err != nil {
		return nil, fmt.Errorf("loading background: %w", err)
	}

	m.Player, err = LoadImage(filepath.Join(basePath, "player.png"))
	if err != nil {
		return nil, fmt.Errorf("loading player: %w", err)
	}

	m.Enemy, err = LoadImage(filepath.Join(basePath, "enemy.png"))
	if err != nil {
		return nil, fmt.Errorf("loading enemy: %w", err)
	}

	return &m, nil
}
