// Code generated by generate_image_loader.go; DO NOT EDIT.
package loader

import (
	"fmt"
	"image"
	"os"
	"path/filepath"

	"github.com/hajimehoshi/ebiten/v2"
)

type BackGroundImages struct {
	OffScreen *ebiten.Image
	OffScreen2 *ebiten.Image
	RoomBackground *ebiten.Image
	FishTank *ebiten.Image
	FishTank_n *ebiten.Image
	FishTankFrontLayerDayLight *ebiten.Image
	FishTankNight *ebiten.Image
	FishTankFrontLayerNoLightSmaller *ebiten.Image
	LaptopRoomBackground *ebiten.Image
}


func LoadImage(path string) (*ebiten.Image, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		return nil, err
	}
	return ebiten.NewImageFromImage(img), nil
}

func LoadAllRoomBackGroundImages(basePath string) (*BackGroundImages, error) {
	var m BackGroundImages
	var err error
 
	m.RoomBackground, err = LoadImage(filepath.Join(basePath, "roomBackground.png"))
	if err != nil {
		return nil, fmt.Errorf("loading roomBackground: %w", err)
	}

	m.FishTank, err = LoadImage(filepath.Join(basePath, "fishTank.png"))
	if err != nil {
		return nil, fmt.Errorf("loading fishTank: %w", err)
	}

	m.FishTank_n, err = LoadImage(filepath.Join(basePath, "fishTank_n.png"))
	if err != nil {
		return nil, fmt.Errorf("loading fishTank_n: %w", err)
	}

	m.FishTankFrontLayerDayLight, err = LoadImage(filepath.Join(basePath, "fishTankFrontLayerDayLight.png"))
	if err != nil {
		return nil, fmt.Errorf("loading fishTankFrontLayerDayLight: %w", err)
	}

	m.FishTankNight, err = LoadImage(filepath.Join(basePath, "fishTankNight.png"))
	if err != nil {
		return nil, fmt.Errorf("loading fishTankNight: %w", err)
	}

	m.FishTankFrontLayerNoLightSmaller, err = LoadImage(filepath.Join(basePath, "fishTankFrontLayerNoLightSmaller.png"))
	if err != nil {
		return nil, fmt.Errorf("loading fishTankFrontLayerNoLightSmaller: %w", err)
	}

	m.LaptopRoomBackground, err = LoadImage(filepath.Join(basePath, "laptopRoomBackground.png"))
	if err != nil {
		return nil, fmt.Errorf("loading laptopRoomBackground: %w", err)
	}

	return &m, nil
}
