package main

import (
	"fmt"
	"os"
	"unicode"
)

func upperFirst(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func main() {
	// Put your image names here
	fields := []string{
		"offScreen",
		"roomBackground",
		"fishTank",
		"frontLayer",
		"fishTank_n",
		"fishTankFrontLayer",
		// Add more as needed
	}

	// Create output file
	f, err := os.Create("game/loader/roomImageLoaderGenerated.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by generate_image_loader.go; DO NOT EDIT.")
	fmt.Fprintln(f, "package loader") // replace with your actual package name
	fmt.Fprintln(f)
	fmt.Fprintln(f, `import (
	"fmt"
	"image"
	"os"
	"path/filepath"

	"github.com/hajimehoshi/ebiten/v2"
)`)
	fmt.Fprintln(f)

	// Generate struct
	fmt.Fprintln(f, "type BackGroundImages struct {")
	for _, field := range fields {
		exportedField := upperFirst(field)
		fmt.Fprintf(f, "	%s *ebiten.Image\n", exportedField)
	}
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)

	// Generate LoadImage helper
	fmt.Fprintln(f, `
func LoadImage(path string) (*ebiten.Image, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		return nil, err
	}
	return ebiten.NewImageFromImage(img), nil
}
`)

	// Generate loader function
	fmt.Fprintln(f, "func LoadAllRoomBackGroundImages(basePath string) (*BackGroundImages, error) {")
	fmt.Fprintln(f, "	var m BackGroundImages")
	fmt.Fprintln(f, "	var err error")
	fmt.Fprintln(f, " ")

	for _, field := range fields {
		if field == "offScreen" {
			continue
		}
		exportedField := upperFirst(field)
		fmt.Fprintf(f, "	m.%s, err = LoadImage(filepath.Join(basePath, \"%s.png\"))\n", exportedField, field)
		fmt.Fprintf(f, "	if err != nil {\n")
		fmt.Fprintf(f, "		return nil, fmt.Errorf(\"loading %s: %%w\", err)\n", field)
		fmt.Fprintf(f, "	}\n\n")
	}

	fmt.Fprintln(f, "	return &m, nil")
	fmt.Fprintln(f, "}")
}
